#include "fractol.h"

#include <stdint.h>

#define TEST_SIZE 32
#define NLM_BENCH_SIZE 192
#define CHANNELS 3

typedef struct s_density_stats
{
	double			sum;
	double			high;
	long double		checksum;
	size_t			nonzero;
}	t_density_stats;

typedef struct s_reference
{
	t_btype			type;
	t_density_stats	channel[CHANNELS];
}	t_reference;

typedef struct s_extent_stats
{
	double		side[2];
	double		boundary[2];
	double		sum;
	double		sum_squares;
	size_t		pixels;
	size_t		nonzero;
	bool		invalid;
}	t_extent_stats;

/*
 * These values are generated by the fixed-seed, single-worker reference cases
 * below and reflect stop-at-escape orbit tracking with exact stratified
 * importance allocation over detected map support.  Parallel determinism is
 * tested separately.
 */
static const t_reference	g_reference[] = {
	{
		BUDDHA1,
		{
			{6132184.9399152165, 13378.996136450494,
				3050170326.44914172776L, 1023},
			{7791925.7631362481, 25662.785745143276,
				3831311210.64001112618L, 1018},
			{8060365.5584335057, 31687.439067077739,
				3954498653.97887994489L, 1018}
		}
	},
	{
		BUDDHA2,
		{
			{1095888.3756980365, 12870.808621797816,
				529780355.046252000757L, 924},
			{476383.40360452246, 9064.0225679049981,
				226935882.799057453813L, 744},
			{899622.68074461783, 14426.210438097787,
				429816454.813835618581L, 766}
		}
	}
};

static void	set_reference_limits(t_fractal *fractal, t_btype type)
{
	if (type == BUDDHA1)
		set_vals(fractal, 0, 0, 0, 50, 500, 5000, &square_complex);
	else
		set_vals(fractal, 20, 55, 55, 350, 500, 3500, &square_complex);
}

static int	setup_case_config_dims(t_fractal *fractal, t_buddha *buddha,
		t_btype type, int workers, int buffers, int width, int height)
{
	memset(fractal, 0, sizeof(*fractal));
	memset(buddha, 0, sizeof(*buddha));
	fractal->width = width;
	fractal->height = height;
	fractal->size = width * height;
	fractal->num_rows = workers;
	fractal->num_cols = 1;
	fractal->bound = 4.0;
	fractal->zoom = 1.2;
	fractal->move_x = -0.21;
	fractal->move_y = 0.0;
	fractal->buffs = buffers;
	fractal->buddha = buddha;
	buddha->type = type;
	buddha->fast = true;
	buddha->n = 2.0;
	buddha->map_n = 1.0;
	buddha->map_adaptive = true;
	buddha->importance_rms = true;
	buddha->square_specialized = true;
	buddha->orbit_cache = true;
	buddha->interior_rejection = true;
	buddha->white_percentile = BUDDHA_WHITE_PERCENTILE;
	buddha->normalization = BUDDHA_NORM_CHANNEL_PERCENTILE;
	buddha->negative_mode = BUDDHA_NEGATIVE_INVERSE;
	buddha->global_exposure = 1.0;
	buddha->hybrid_spill = BUDDHA_HYBRID_SPILL;
	buddha->hybrid_background = BUDDHA_HYBRID_BACKGROUND;
	buddha->hybrid_foreground = BUDDHA_HYBRID_FOREGROUND;
	buddha->nlm_enabled = (buffers > 1);
	buddha->nlm_smooth_var = true;
	buddha->nlm_patch_radius = 1;
	buddha->nlm_search_radius = 2;
	buddha->nlm_kc = 1.0;
	buddha->nlm_noise_scale = 1.0 / (double)buffers;
	buddha->nlm_noise_floor = 1.0 / (255.0 * 255.0);
	buddha->nlm_r_weight = 1.0;
	buddha->nlm_g_weight = 1.0;
	buddha->nlm_b_weight = 1.0;
	fractal->histograms = CHANNELS * buffers;
	if (buddha->nlm_enabled && fractal->histograms < BUDDHA_NLM_MATRICES)
		fractal->histograms = BUDDHA_NLM_MATRICES;
	fractal->threads = malloc((size_t)workers * sizeof(*fractal->threads));
	if (!fractal->threads)
		return (-1);
	set_reference_limits(fractal, type);
	init_matricies(fractal);
	return (0);
}

static int	setup_case_config_size(t_fractal *fractal, t_buddha *buddha,
		t_btype type, int workers, int buffers, int size)
{
	return (setup_case_config_dims(fractal, buddha, type, workers, buffers,
			size, size));
}

static int	setup_case_config(t_fractal *fractal, t_buddha *buddha,
		t_btype type, int workers, int buffers)
{
	return (setup_case_config_size(fractal, buddha, type, workers,
			buffers, TEST_SIZE));
}

static int	setup_case_workers(t_fractal *fractal, t_buddha *buddha,
		t_btype type, int workers)
{
	return (setup_case_config(fractal, buddha, type, workers, 1));
}

static int	setup_case(t_fractal *fractal, t_buddha *buddha, t_btype type)
{
	return (setup_case_workers(fractal, buddha, type, 1));
}

static void	teardown_case(t_fractal *fractal)
{
	free_matrices(fractal);
	free(fractal->threads);
}

static t_density_stats	measure_density(double **density)
{
	t_density_stats	stats;
	int				x;
	int				y;

	memset(&stats, 0, sizeof(stats));
	y = -1;
	while (++y < TEST_SIZE)
	{
		x = -1;
		while (++x < TEST_SIZE)
		{
			stats.sum += density[y][x];
			if (density[y][x] > stats.high)
				stats.high = density[y][x];
			if (density[y][x] != 0.0)
				stats.nonzero++;
			stats.checksum += (long double)density[y][x]
				* (long double)(1 + x + y * TEST_SIZE);
		}
	}
	return (stats);
}

static void	print_stats(t_btype type, int channel, t_density_stats stats)
{
	printf("type=%d channel=%d sum=%.17g high=%.17g "
		"checksum=%.21Lg nonzero=%zu\n", type, channel, stats.sum,
		stats.high, stats.checksum, stats.nonzero);
}

static int	close_enough(long double actual, long double expected)
{
	long double	scale;

	scale = fabsl(expected);
	if (scale < 1.0L)
		scale = 1.0L;
	return (fabsl(actual - expected) <= scale * 1e-12L);
}

static int	matches_reference(t_density_stats actual,
		t_density_stats expected)
{
	return (close_enough(actual.sum, expected.sum)
		&& close_enough(actual.high, expected.high)
		&& close_enough(actual.checksum, expected.checksum)
		&& actual.nonzero == expected.nonzero);
}

static int	run_case(const t_reference *reference, int print_reference)
{
	t_fractal			fractal;
	t_buddha			buddha;
	t_density_stats	stats;
	int					channel;
	int					failed;

	if (setup_case(&fractal, &buddha, reference->type) != 0)
		return (fprintf(stderr, "Buddha regression setup failed\n"), 1);
	failed = 0;
	channel = -1;
	while (++channel < CHANNELS)
	{
		buddha_render_channel(&fractal,
			((int [CHANNELS]){fractal.buddha->min1, fractal.buddha->min2,
				fractal.buddha->min3})[channel],
			((int [CHANNELS]){fractal.buddha->max1, fractal.buddha->max2,
				fractal.buddha->max3})[channel], channel);
		stats = measure_density(fractal.densities[channel]);
		if (print_reference)
			print_stats(reference->type, channel, stats);
		else if (!matches_reference(stats, reference->channel[channel]))
		{
			print_stats(reference->type, channel, stats);
			failed = 1;
		}
	}
	teardown_case(&fractal);
	return (failed);
}

static int	test_tone_mapping(void)
{
	t_buddha	buddha;
	double	values[10] = {10.0, 1.0, 9.0, 2.0, 8.0,
		3.0, 7.0, 4.0, 6.0, 5.0};
	double	sparse[10] = {0.0};
	double	blue_values[4] = {1.0, 4.0, 0.0, 2.0};
	double	green_values[4] = {2.0, 1.0, 0.0, 8.0};
	double	red_values[4] = {0.5, 3.0, 0.0, 1.0};
	double	*blue[1] = {blue_values};
	double	*green[1] = {green_values};
	double	*red[1] = {red_values};
	double	**rgb[3] = {blue, green, red};
	double	*matrix[1];
	double	percentile;
	double	mapped;

	matrix[0] = values;
	percentile = buddha_density_percentile(matrix, 10, 1, 0.8);
	if (percentile != 8.0)
		return (fprintf(stderr, "Unexpected Buddha percentile: %.17g\n",
				percentile), 1);
	sparse[9] = 42.0;
	matrix[0] = sparse;
	percentile = buddha_density_percentile(matrix, 10, 1, 0.8);
	if (percentile != 42.0)
		return (fprintf(stderr, "Sparse Buddha percentile was zero\n"), 1);
	matrix[0] = values;
	mapped = buddha_tone_value(percentile, percentile,
			0.5, 0.2, 0.8, 0.8);
	if (!close_enough(mapped, 1.0L))
		return (fprintf(stderr, "White point did not map to white: %.17g\n",
				mapped), 1);
	mapped = buddha_tone_value(percentile, percentile,
			0.5, 0.2, 1.0, 0.8);
	if (mapped <= 0.0 || mapped >= 1.0)
		return (fprintf(stderr, "Tone edge no longer controls clipping\n"), 1);
	mapped = buddha_tone_value(0.0, percentile, 0.5, 0.2, 0.8, 0.8);
	if (mapped != 0.0)
		return (fprintf(stderr, "Zero density did not map to black\n"), 1);
	mapped = buddha_curve_value(1.0, 10.0, -0.5);
	if (mapped <= 0.0 || mapped >= 1.0
		|| buddha_curve_value(10.0, 10.0, -0.5) != 0.0
		|| buddha_curve_value(0.0, 10.0, -0.5) != 0.0)
		return (fprintf(stderr, "Signed inverse tone curve failed\n"), 1);
	if (buddha_legacy_spill_color(25.0, 100.0, -0.5,
			1.0, 0) != 0x000001FEu
		|| buddha_legacy_spill_color(25.0, 100.0, -0.5,
			1.0, 8) != 0x0001FE00u
		|| buddha_legacy_spill_color(25.0, 100.0, -0.5,
			1.0, 16) != 0x00FE0000u
		|| buddha_legacy_spill_color(0.0, 100.0, -0.5,
			1.0, 0) != 0)
		return (fprintf(stderr, "Legacy channel spill mapping failed\n"), 1);
	if (!close_enough(buddha_adjust_power(0.07, -1.0,
				false, false), 0.02)
		|| !close_enough(buddha_adjust_power(-0.07, 1.0,
				false, false), -0.02)
		|| !close_enough(buddha_adjust_power(-0.01, 1.0,
				false, false), 0.05)
		|| !close_enough(buddha_adjust_power(-0.05, 1.0,
				true, false), -0.04)
		|| !close_enough(buddha_adjust_power(-0.001, 1.0,
				true, true), 0.001)
		|| !close_enough(buddha_adjust_power(-0.2, -1.0,
				false, false), -0.25)
		|| !close_enough(buddha_adjust_power(-0.2, 1.0,
				true, false), -0.19)
		|| !close_enough(buddha_adjust_power(-0.2, 1.0,
				false, true), -0.199))
		return (fprintf(stderr, "Near-zero power adjustment failed\n"), 1);
	rgb[0][0] = blue_values;
	rgb[1][0] = green_values;
	rgb[2][0] = red_values;
	percentile = buddha_density_percentile_rgb(rgb, 4, 1, 0.75);
	if (percentile != 4.0)
		return (fprintf(stderr, "Unexpected linked percentile: %.17g\n",
				percentile), 1);
	memset(&buddha, 0, sizeof(buddha));
	buddha.bpow = 0.4;
	buddha.gpow = 0.5;
	buddha.rpow = 0.6;
	buddha.global_exposure = 1.0;
	buddha.white_percentile = 0.999;
	buddha.normalization = BUDDHA_NORM_CHANNEL_PERCENTILE;
	buddha_tone_store_defaults(&buddha);
	buddha.bpow = -0.4;
	buddha.normalization = BUDDHA_NORM_LEGACY_MAX;
	buddha.negative_mode = BUDDHA_NEGATIVE_SPILL;
	buddha.hybrid_spill = 0.35;
	buddha_tone_swap_alternate(&buddha);
	if (buddha.bpow != 0.4
		|| buddha.normalization != BUDDHA_NORM_CHANNEL_PERCENTILE
		|| buddha.negative_mode != BUDDHA_NEGATIVE_INVERSE
		|| buddha.hybrid_spill != 0.0)
		return (fprintf(stderr, "Tone A/B first swap failed\n"), 1);
	buddha_tone_swap_alternate(&buddha);
	if (buddha.bpow != -0.4
		|| buddha.normalization != BUDDHA_NORM_LEGACY_MAX
		|| buddha.negative_mode != BUDDHA_NEGATIVE_SPILL
		|| buddha.hybrid_spill != 0.35)
		return (fprintf(stderr, "Tone A/B second swap failed\n"), 1);
	buddha_tone_reset(&buddha);
	if (buddha.bpow != 0.4
		|| buddha.normalization != BUDDHA_NORM_CHANNEL_PERCENTILE
		|| buddha.negative_mode != BUDDHA_NEGATIVE_INVERSE
		|| buddha.hybrid_spill != 0.0)
		return (fprintf(stderr, "Tone reset failed\n"), 1);
	return (0);
}

static int	test_post_spill_smoother(void)
{
	t_fractal		fractal;
	t_buddha		buddha;
	unsigned int	pixel;

	if (setup_case_config_size(&fractal, &buddha, BUDDHA1, 1, 1, 1) != 0)
		return (fprintf(stderr, "Post-spill setup failed\n"), 1);
	pixel = 0;
	fractal.img = (t_img){NULL, (char *)&pixel, 32, 0, 4};
	buddha.bpow = -0.5;
	buddha.gpow = 0.5;
	buddha.rpow = 0.5;
	buddha.high_b = 100.0;
	buddha.high_g = 100.0;
	buddha.high_r = 100.0;
	buddha.white_b = 100.0;
	buddha.white_g = 100.0;
	buddha.white_r = 100.0;
	buddha.exposure_b = 1.0;
	buddha.exposure_g = 1.0;
	buddha.exposure_r = 1.0;
	buddha.global_exposure = 1.0;
	buddha.edge0_b = 0.2;
	buddha.edge0_g = 0.2;
	buddha.edge0_r = 0.2;
	buddha.edge1_b = 0.8;
	buddha.edge1_g = 0.8;
	buddha.edge1_r = 0.8;
	buddha.negative_mode = BUDDHA_NEGATIVE_SPILL;
	buddha.smootherstep = true;
	buddha_tone_store_defaults(&buddha);
	fractal.densities[0][0][0] = 25.0;
	color_buddha(&fractal);
	teardown_case(&fractal);
	if (pixel != 0x000000FFu)
		return (fprintf(stderr,
				"Post-spill smootherstep failed: 0x%08X\n", pixel), 1);
	return (0);
}

static int	test_hybrid_tone(void)
{
	t_fractal		fractal;
	t_buddha		buddha;
	unsigned int	pixels[4];
	int				channel;

	if (setup_case_config_size(&fractal, &buddha, BUDDHA1, 1, 1, 2) != 0)
		return (fprintf(stderr, "Hybrid tone setup failed\n"), 1);
	memset(pixels, 0, sizeof(pixels));
	fractal.img = (t_img){NULL, (char *)pixels, 32, 0, 8};
	buddha.bpow = -0.5;
	buddha.gpow = -0.5;
	buddha.rpow = -0.5;
	buddha.exposure_b = 1.0;
	buddha.exposure_g = 1.0;
	buddha.exposure_r = 1.0;
	buddha.global_exposure = 1.0;
	buddha.negative_mode = BUDDHA_NEGATIVE_HYBRID;
	buddha.hybrid_spill = 0.0;
	buddha.hybrid_background = BUDDHA_HYBRID_BACKGROUND;
	buddha.hybrid_foreground = BUDDHA_HYBRID_FOREGROUND;
	buddha.smootherstep = false;
	buddha_tone_store_defaults(&buddha);
	channel = -1;
	while (++channel < 3)
		fractal.densities[channel][0][1] = 100.0;
	buddha.white_b = 100.0;
	buddha.white_g = 100.0;
	buddha.white_r = 100.0;
	color_buddha(&fractal);
	teardown_case(&fractal);
	if (pixels[0] != BUDDHA_HYBRID_BACKGROUND
		|| pixels[1] != BUDDHA_HYBRID_FOREGROUND)
		return (fprintf(stderr,
				"Hybrid tone endpoints failed: 0x%06X 0x%06X\n",
				pixels[0], pixels[1]), 1);
	return (0);
}

static int	verify_importance_allocation(t_fractal *fractal)
{
	size_t	budget;
	size_t	allocated;
	size_t	index;
	uint32_t	samples;

	budget = buddha_sample_budget(fractal);
	allocated = 0;
	index = 0;
	while (index < (size_t)fractal->size)
	{
		samples = fractal->sample_counts[index];
		allocated += (size_t)samples;
		index++;
	}
	if (allocated != budget)
		return (fprintf(stderr,
				"Importance allocation budget mismatch: %zu != %zu\n",
				allocated, budget), 1);
	return (0);
}

static int	test_sample_budget_guard(void)
{
	t_fractal	fractal;
	t_buddha	buddha;

	memset(&fractal, 0, sizeof(fractal));
	memset(&buddha, 0, sizeof(buddha));
	fractal.buddha = &buddha;
	fractal.size = 64;
	fractal.buffs = 3;
	buddha.n = 8.0;
	if (buddha_sample_budget(&fractal) != 1365)
		return (fprintf(stderr, "Buddha sample budget rounding changed\n"), 1);
	buddha.n = (double)UINT32_MAX;
	if (buddha_sample_budget(&fractal) != SIZE_MAX)
		return (fprintf(stderr,
				"Oversized Buddha sample budget was not rejected\n"), 1);
	return (0);
}

static int	test_buddha_start_options(void)
{
	char		*valid[] = {"--zoom", "2.5", "--importance-map",
		"--center", "0.125", "-0.75"};
	char		*bad_zoom[] = {"--zoom", "0"};
	char		*bad_center[] = {"--center", "nan", "0"};
	char		*duplicate[] = {"--zoom", "2", "--zoom", "3"};
	t_fractal	fractal;
	t_buddha	buddha;
	int			failed;

	memset(&fractal, 0, sizeof(fractal));
	memset(&buddha, 0, sizeof(buddha));
	fractal.buddha = &buddha;
	fractal.move_x = -0.21;
	fractal.move_y = 0.0;
	fractal.zoom = 1.2;
	failed = parse_buddha_options(&buddha, 6, valid) != 0;
	buddha_apply_start_view(&fractal);
	failed |= !buddha.importance_enabled || !buddha.view_center_set
		|| !buddha.view_zoom_set;
	failed |= fractal.move_x != 0.125 || fractal.move_y != 0.75
		|| fractal.zoom != 2.5;
	memset(&buddha, 0, sizeof(buddha));
	failed |= parse_buddha_options(&buddha, 2, bad_zoom) == 0;
	memset(&buddha, 0, sizeof(buddha));
	failed |= parse_buddha_options(&buddha, 3, bad_center) == 0;
	memset(&buddha, 0, sizeof(buddha));
	failed |= parse_buddha_options(&buddha, 4, duplicate) == 0;
	if (failed)
		fprintf(stderr, "Buddha startup view option regression failed\n");
	return (failed);
}

static int	test_importance_allocation(void)
{
	t_fractal	fractal;
	t_buddha	buddha;
	uint32_t	first_count;
	uint32_t	middle_count;
	uint32_t	last_count;
	int			failed;

	if (setup_case(&fractal, &buddha, BUDDHA1) != 0)
		return (fprintf(stderr, "Importance allocation setup failed\n"), 1);
	zero_matrix(fractal.densities[0], fractal.width, fractal.height);
	fractal.densities[0][0][0] = NAN;
	fractal.densities[0][0][1] = -10.0;
	fractal.densities[0][fractal.height / 2][fractal.width / 2] = 100.0;
	build_importance_map(&fractal, fractal.densities[0]);
	failed = verify_importance_allocation(&fractal);
	first_count = fractal.sample_counts[0];
	middle_count = fractal.sample_counts[(size_t)(fractal.height / 2)
		* (size_t)fractal.width + (size_t)(fractal.width / 2)];
	last_count = fractal.sample_counts[(size_t)fractal.size - 1];
	if (first_count != 0 || last_count != 0 || middle_count == 0)
	{
		fprintf(stderr,
			"Importance allocation sampled unusable map cells\n");
		failed = 1;
	}
	zero_matrix(fractal.densities[0], fractal.width, fractal.height);
	build_importance_map(&fractal, fractal.densities[0]);
	failed |= verify_importance_allocation(&fractal);
	first_count = fractal.sample_counts[0];
	last_count = fractal.sample_counts[(size_t)fractal.size - 1];
	if ((first_count > last_count && first_count - last_count > 1)
		|| (last_count > first_count && last_count - first_count > 1))
	{
		fprintf(stderr, "Zero importance map did not fall back uniformly\n");
		failed = 1;
	}
	teardown_case(&fractal);
	return (failed);
}

static void	set_test_channel(t_fractal *fractal, int channel)
{
	t_buddha	*b;

	b = fractal->buddha;
	fractal->hist_num = channel;
	if (channel == 0)
	{
		fractal->b_min_i = b->min1;
		fractal->b_max_i = b->max1;
	}
	else if (channel == 1)
	{
		fractal->b_min_i = b->min2;
		fractal->b_max_i = b->max2;
	}
	else
	{
		fractal->b_min_i = b->min3;
		fractal->b_max_i = b->max3;
	}
}

static int	test_combined_map_equivalence(void)
{
	t_fractal	fractal;
	t_buddha	buddha;
	double		*separate;
	size_t		channel_bytes;
	int			channel;
	int			x;
	int			y;
	int			failed;
	int			rms_different;

	if (setup_case_workers(&fractal, &buddha, BUDDHA1, 4) != 0)
		return (fprintf(stderr, "Combined-map setup failed\n"), 1);
	buddha.map_n = 2.0;
	buddha.map_adaptive = false;
	buddha.importance_rms = false;
	channel_bytes = (size_t)fractal.size * sizeof(*separate);
	separate = malloc(3 * channel_bytes);
	if (!separate)
	{
		teardown_case(&fractal);
		return (fprintf(stderr, "Combined-map snapshot failed\n"), 1);
	}
	channel = -1;
	while (++channel < 3)
	{
		set_test_channel(&fractal, channel);
		zero_matrix(fractal.densities[channel],
			fractal.width, fractal.height);
		buddha_map(&fractal);
		y = -1;
		while (++y < fractal.height)
			memcpy(separate + (size_t)channel * (size_t)fractal.size
				+ (size_t)y * (size_t)fractal.width,
				fractal.densities[channel][y],
				(size_t)fractal.width * sizeof(*separate));
	}
	channel = -1;
	while (++channel < 3)
		zero_matrix(fractal.densities[channel],
			fractal.width, fractal.height);
	buddha_map_all(&fractal);
	failed = 0;
	channel = -1;
	while (++channel < 3)
	{
		y = -1;
		while (++y < fractal.height)
		{
			if (memcmp(separate + (size_t)channel * (size_t)fractal.size
					+ (size_t)y * (size_t)fractal.width,
					fractal.densities[channel][y],
					(size_t)fractal.width * sizeof(*separate)) != 0)
			{
				fprintf(stderr,
					"Combined importance map changed channel %d\n", channel);
				failed = 1;
				channel = 3;
				break ;
			}
		}
	}
	buddha.importance_rms = true;
	set_test_channel(&fractal, 2);
	buddha_map(&fractal);
	rms_different = 0;
	y = -1;
	while (++y < fractal.height)
	{
		x = -1;
		while (++x < fractal.width)
		{
			if (!isfinite(fractal.densities[2][y][x])
				|| fractal.densities[2][y][x] < 0.0)
			{
				fprintf(stderr, "RMS importance map contains invalid values\n");
				failed = 1;
				y = fractal.height;
				break ;
			}
			if (fractal.densities[2][y][x] != separate[
					2 * (size_t)fractal.size
					+ (size_t)y * (size_t)fractal.width + (size_t)x])
				rms_different = 1;
		}
	}
	if (!rms_different)
	{
		fprintf(stderr, "RMS importance metric did not use the second moment\n");
		failed = 1;
	}
	free(separate);
	teardown_case(&fractal);
	return (failed);
}

static int	test_map_scale_policy(void)
{
	t_fractal	fractal;
	t_buddha	buddha;
	int			failed;

	memset(&fractal, 0, sizeof(fractal));
	memset(&buddha, 0, sizeof(buddha));
	fractal.buddha = &buddha;
	fractal.width = 1080;
	fractal.height = 1080;
	buddha.map_n = 5.0;
	buddha.map_adaptive = true;
	failed = 0;
	if (buddha_map_scale(&fractal) != 3)
	{
		fprintf(stderr, "Adaptive 1080p map scale was not 3\n");
		failed = 1;
	}
	buddha.map_adaptive = false;
	if (buddha_map_scale(&fractal) != 5)
	{
		fprintf(stderr, "Fixed map scale did not preserve map_n\n");
		failed = 1;
	}
	return (failed);
}

static int	check_aspect_geometry(int width, int height)
{
	t_fractal	fractal;
	t_buddha	buddha;
	t_comps	comps;
	t_complex	first;
	t_complex	last;
	double		expected_scale_ratio;
	double		pixel_scale_x;
	double		pixel_scale_y;
	double		sample_density;
	double		sample_pixel_area;
	int			failed;

	memset(&fractal, 0, sizeof(fractal));
	memset(&buddha, 0, sizeof(buddha));
	fractal.width = width;
	fractal.height = height;
	fractal.size = width * height;
	fractal.zoom = 1.2;
	fractal.buddha = &buddha;
	buddha.n = 2.0;
	buddha.map_n = 1.0;
	comps = set_comps(&fractal, false);
	failed = 0;
	pixel_scale_x = fabs(comps.slopex_to);
	pixel_scale_y = fabs(comps.slopey_to);
	expected_scale_ratio = ((double)(height - 1) / (double)height)
		/ ((double)(width - 1) / (double)width);
	sample_density = comps.samples
		/ fabs(comps.sample_x_span * comps.sample_y_span);
	sample_pixel_area = pixel_scale_x * pixel_scale_y;
	first = buddha_sample_point(comps, 0.0, 0.0);
	last = buddha_sample_point(comps, (double)width, (double)height);
	if (!close_enough(fabsl(comps.slopex_back),
			fabsl(comps.slopey_back))
		|| !close_enough(comps.sample_x_span, comps.x_span)
		|| !close_enough(comps.sample_y_span, comps.y_span)
		|| !close_enough(first.x, comps.sample_x_min)
		|| !close_enough(first.y, comps.sample_y_min)
		|| !close_enough(last.x,
			comps.sample_x_min + comps.sample_x_span)
		|| !close_enough(last.y,
			comps.sample_y_min + comps.sample_y_span)
		|| !close_enough(pixel_scale_x / pixel_scale_y,
			expected_scale_ratio)
		|| !close_enough(sample_density * sample_pixel_area,
			buddha.n * buddha.n))
	{
		fprintf(stderr, "Buddha aspect geometry failed at %dx%d\n",
			width, height);
		failed = 1;
	}
	if ((width >= height && (!close_enough(comps.x_span, 4.0L)
				|| fabsl(comps.y_span) < 4.0L))
		|| (height >= width && (!close_enough(comps.y_span, -4.0L)
				|| comps.x_span < 4.0L)))
	{
		fprintf(stderr, "Buddha aspect span failed at %dx%d\n",
			width, height);
		failed = 1;
	}
	return (failed);
}

static int	check_rectangular_map_symmetry(t_btype type,
		int width, int height)
{
	t_fractal	fractal;
	t_buddha	buddha;
	int			x;
	int			y;
	int			failed;

	if (setup_case_config_dims(&fractal, &buddha, type, 2, 1,
			width, height) != 0)
		return (fprintf(stderr,
				"Rectangular symmetry setup failed\n"), 1);
	buddha.map_n = 2.0;
	buddha.map_adaptive = false;
	set_test_channel(&fractal, 0);
	zero_matrix(fractal.densities[0], width, height);
	buddha_map(&fractal);
	failed = 0;
	y = -1;
	while (++y < height)
	{
		x = -1;
		while (++x < width / 2)
		{
			if (fractal.densities[0][y][x]
				!= fractal.densities[0][y][width - 1 - x])
			{
				failed = 1;
				break ;
			}
		}
		if (failed)
			break ;
	}
	if (failed)
		fprintf(stderr, "Rectangular importance symmetry failed at "
			"%dx%d type %d\n", width, height, type);
	teardown_case(&fractal);
	return (failed);
}

static t_extent_stats	measure_extended_axis(t_fractal *fractal, int channel)
{
	t_extent_stats	stats;
	double			value;
	int				offset;
	int				x;
	int				y;

	memset(&stats, 0, sizeof(stats));
	offset = abs(fractal->height - fractal->width) / 2;
	y = -1;
	while (++y < fractal->height)
	{
		x = -1;
		while (++x < fractal->width)
		{
			value = fractal->densities[channel][y][x];
			if (!isfinite(value) || value < 0.0)
				stats.invalid = true;
			if ((fractal->height > fractal->width
					&& (y < offset || y >= offset + fractal->width))
				|| (fractal->width > fractal->height
					&& (x < offset || x >= offset + fractal->height)))
			{
				stats.side[(fractal->height > fractal->width
						&& y >= offset + fractal->width)
					|| (fractal->width > fractal->height
						&& x >= offset + fractal->height)] += value;
				stats.sum += value;
				stats.sum_squares += value * value;
				stats.pixels++;
				stats.nonzero += (value > 0.0);
			}
			if ((fractal->height > fractal->width
					&& (y == offset - 1
						|| y == offset + fractal->width))
				|| (fractal->width > fractal->height
					&& (x == offset - 1
						|| x == offset + fractal->height)))
				stats.boundary[(fractal->height > fractal->width
						&& y == offset + fractal->width)
					|| (fractal->width > fractal->height
						&& x == offset + fractal->height)] += value;
		}
	}
	return (stats);
}

static int	validate_extended_axis(t_fractal *fractal, int channel,
		char *stage)
{
	t_extent_stats	stats;
	double			variance;

	stats = measure_extended_axis(fractal, channel);
	variance = 0.0;
	if (stats.pixels > 0)
		variance = stats.sum_squares / (double)stats.pixels
			- (stats.sum / (double)stats.pixels)
			* (stats.sum / (double)stats.pixels);
	if (stats.invalid || stats.side[0] <= 0.0 || stats.side[1] <= 0.0
		|| stats.boundary[0] <= 0.0 || stats.boundary[1] <= 0.0
		|| stats.nonzero == 0 || variance <= 0.0)
		return (fprintf(stderr,
				"Rectangular %s coverage failed at %dx%d type %d channel %d\n",
				stage, fractal->width, fractal->height,
				fractal->buddha->type, channel), 1);
	return (0);
}

static int	check_rectangular_render(t_btype type, int width, int height)
{
	t_fractal	fractal;
	t_buddha	buddha;
	int			failed;

	if (setup_case_config_dims(&fractal, &buddha, type, 2, 1,
			width, height) != 0)
		return (fprintf(stderr, "Rectangular Buddha setup failed\n"), 1);
	failed = check_aspect_geometry(width, height);
	buddha_render_channel(&fractal, buddha.min1, buddha.max1, 0);
	failed |= validate_extended_axis(&fractal, 0, "raw");
	teardown_case(&fractal);
	return (failed);
}

static int	check_rectangular_determinism(t_btype type, int width, int height)
{
	t_fractal	fractal;
	t_buddha	buddha;
	double		*reference;
	size_t		bytes;
	int			y;
	int			failed;

	if (setup_case_config_dims(&fractal, &buddha, type, 4, 1,
			width, height) != 0)
		return (fprintf(stderr,
				"Rectangular determinism setup failed\n"), 1);
	bytes = (size_t)fractal.size * sizeof(*reference);
	reference = malloc(bytes);
	if (!reference)
		return (teardown_case(&fractal), 1);
	buddha_render_channel(&fractal, buddha.min1, buddha.max1, 0);
	y = -1;
	while (++y < height)
		memcpy(reference + (size_t)y * (size_t)width,
			fractal.densities[0][y], (size_t)width * sizeof(*reference));
	buddha_render_channel(&fractal, buddha.min1, buddha.max1, 0);
	failed = 0;
	y = -1;
	while (++y < height)
		if (memcmp(reference + (size_t)y * (size_t)width,
				fractal.densities[0][y],
				(size_t)width * sizeof(*reference)) != 0)
			failed = 1;
	if (failed)
		fprintf(stderr, "Rectangular render was not deterministic at "
			"%dx%d type %d\n", width, height, type);
	free(reference);
	teardown_case(&fractal);
	return (failed);
}

static int	check_rectangular_nlm(t_btype type, int width, int height)
{
	t_fractal	fractal;
	t_buddha	buddha;
	int			minimum[CHANNELS];
	int			maximum[CHANNELS];
	int			channel;
	int			failed;

	if (setup_case_config_dims(&fractal, &buddha, type, 2, 3,
			width, height) != 0)
		return (fprintf(stderr, "Rectangular NLM setup failed\n"), 1);
	minimum[0] = buddha.min1;
	minimum[1] = buddha.min2;
	minimum[2] = buddha.min3;
	maximum[0] = buddha.max1;
	maximum[1] = buddha.max2;
	maximum[2] = buddha.max3;
	channel = -1;
	while (++channel < CHANNELS)
		buddha_render_channel(&fractal, minimum[channel],
			maximum[channel], channel);
	failed = validate_extended_axis(&fractal, 0, "raw multibuffer");
	if (buddha_nlm(&fractal) != 0)
		failed = 1;
	else
		failed |= validate_extended_axis(&fractal, 0, "NLM");
	teardown_case(&fractal);
	return (failed);
}

static int	test_aspect_geometry_matrix(void)
{
	static const int	dimensions[][2] = {
		{48, 48}, {60, 48}, {48, 60}, {64, 48}, {48, 64},
		{72, 48}, {48, 72}, {80, 45}, {45, 80}, {96, 48}, {48, 96}
	};
	int				failed;
	size_t			index;

	failed = 0;
	index = 0;
	while (index < sizeof(dimensions) / sizeof(dimensions[0]))
	{
		failed |= check_aspect_geometry(
				dimensions[index][0], dimensions[index][1]);
		index++;
	}
	return (failed);
}

static int	test_rectangular_geometry_and_display(void)
{
	t_fractal	fractal;
	int			x;
	int			y;
	int			failed;

	failed = 0;
	failed |= test_aspect_geometry_matrix();
	failed |= check_rectangular_render(BUDDHA1, 60, 48);
	failed |= check_rectangular_render(BUDDHA1, 48, 96);
	failed |= check_rectangular_render(BUDDHA2, 80, 45);
	failed |= check_rectangular_render(BUDDHA2, 48, 72);
	failed |= check_rectangular_map_symmetry(BUDDHA1, 64, 48);
	failed |= check_rectangular_map_symmetry(BUDDHA1, 48, 64);
	failed |= check_rectangular_map_symmetry(BUDDHA2, 72, 48);
	failed |= check_rectangular_map_symmetry(BUDDHA2, 48, 72);
	failed |= check_rectangular_determinism(BUDDHA1, 72, 48);
	failed |= check_rectangular_determinism(BUDDHA2, 48, 64);
	failed |= check_rectangular_nlm(BUDDHA1, 64, 48);
	failed |= check_rectangular_nlm(BUDDHA2, 48, 64);
	if (!buddha_should_rotate_display(600, 1200, 1080)
		|| buddha_should_rotate_display(1200, 600, 1080)
		|| buddha_should_rotate_display(600, 1080, 1080))
	{
		fprintf(stderr, "Oversized portrait display policy is incorrect\n");
		failed = 1;
	}
	memset(&fractal, 0, sizeof(fractal));
	fractal.display_rotated = true;
	fractal.height_orig = 7;
	x = 1;
	y = 2;
	display_to_render_coordinates(&fractal, &x, &y);
	if (x != 2 || y != 5)
	{
		fprintf(stderr, "Clockwise display coordinate inverse is incorrect\n");
		failed = 1;
	}
	return (failed);
}

static int	test_square_specialization(void)
{
	t_fractal	fractal;
	t_buddha	buddha;
	double		*specialized;
	size_t		bytes;
	int			y;
	int			failed;

	if (setup_case(&fractal, &buddha, BUDDHA1) != 0)
		return (fprintf(stderr, "Square specialization setup failed\n"), 1);
	bytes = (size_t)fractal.size * sizeof(*specialized);
	specialized = malloc(bytes);
	if (!specialized)
	{
		teardown_case(&fractal);
		return (fprintf(stderr, "Square specialization snapshot failed\n"), 1);
	}
	buddha.orbit_cache = false;
	buddha.interior_rejection = false;
	buddha_render_channel(&fractal, buddha.min2, buddha.max2, 1);
	y = -1;
	while (++y < fractal.height)
		memcpy(specialized + (size_t)y * (size_t)fractal.width,
			fractal.densities[1][y],
			(size_t)fractal.width * sizeof(*specialized));
	buddha.orbit_cache = true;
	buddha.interior_rejection = true;
	buddha_render_channel(&fractal, buddha.min2, buddha.max2, 1);
	failed = 0;
	y = -1;
	while (++y < fractal.height)
	{
		if (memcmp(specialized + (size_t)y * (size_t)fractal.width,
				fractal.densities[1][y],
				(size_t)fractal.width * sizeof(*specialized)) != 0)
		{
			fprintf(stderr,
				"Cached/interior-rejected orbit changed the rendered density\n");
			failed = 1;
			break ;
		}
	}
	buddha.orbit_cache = false;
	buddha.interior_rejection = false;
	buddha.square_specialized = false;
	buddha_render_channel(&fractal, buddha.min2, buddha.max2, 1);
	y = -1;
	while (++y < fractal.height)
	{
		if (memcmp(specialized + (size_t)y * (size_t)fractal.width,
				fractal.densities[1][y],
				(size_t)fractal.width * sizeof(*specialized)) != 0)
		{
			fprintf(stderr,
				"Square specialization changed the rendered density\n");
			failed = 1;
			break ;
		}
	}
	free(specialized);
	teardown_case(&fractal);
	return (failed);
}

static int	verify_worker_reduction(t_fractal *fractal, int channel,
		int buffer)
{
	double	expected;
	size_t	index;
	int		worker;
	int		x;
	int		y;

	index = 0;
	y = -1;
	while (++y < fractal->height)
	{
		x = -1;
		while (++x < fractal->width)
		{
			expected = 0.0;
			worker = -1;
			while (++worker < fractal->worker_histogram_count)
				expected += fractal->worker_histograms[worker][index];
			if (fractal->densities[channel + buffer * CHANNELS][y][x]
				!= expected)
				return (fprintf(stderr,
						"Worker reduction mismatch at (%d, %d)\n", x, y), 1);
			index++;
		}
	}
	return (0);
}

static int	test_parallel_determinism(void)
{
	t_fractal	fractal;
	t_buddha	buddha;
	double		*reference;
	size_t		bytes;
	int			y;
	int			failed;

	if (setup_case_workers(&fractal, &buddha, BUDDHA1, 4) != 0)
		return (fprintf(stderr, "Parallel Buddha setup failed\n"), 1);
	bytes = (size_t)fractal.size * sizeof(*reference);
	reference = malloc(bytes);
	if (!reference)
	{
		teardown_case(&fractal);
		return (fprintf(stderr, "Parallel Buddha snapshot failed\n"), 1);
	}
	buddha_render_channel(&fractal, buddha.min1, buddha.max1, 0);
	failed = verify_worker_reduction(&fractal, 0, 0);
	y = -1;
	while (++y < fractal.height)
		memcpy(reference + (size_t)y * (size_t)fractal.width,
			fractal.densities[0][y],
			(size_t)fractal.width * sizeof(*reference));
	buddha_render_channel(&fractal, buddha.min1, buddha.max1, 0);
	failed |= verify_worker_reduction(&fractal, 0, 0);
	y = -1;
	while (++y < fractal.height)
	{
		if (memcmp(reference + (size_t)y * (size_t)fractal.width,
				fractal.densities[0][y],
				(size_t)fractal.width * sizeof(*reference)) != 0)
		{
			fprintf(stderr,
				"Parallel Buddha render was not bit-for-bit deterministic\n");
			failed = 1;
			break ;
		}
	}
	free(reference);
	teardown_case(&fractal);
	return (failed);
}

static int	test_multibuffer_reduction_and_variance(void)
{
	t_fractal	fractal;
	t_buddha	buddha;
	double		expected;
	int			buffer;
	int			worker;
	int			failed;

	if (setup_case_config(&fractal, &buddha, BUDDHA1, 3, 3) != 0)
		return (fprintf(stderr, "Multibuffer Buddha setup failed\n"), 1);
	failed = 0;
	fractal.hist_num = 0;
	buffer = -1;
	while (++buffer < fractal.buffs)
	{
		worker = -1;
		while (++worker < fractal.worker_histogram_count)
			fractal.worker_histograms[worker][0]
				= (double)(1 + worker + buffer * 10);
		buddha_reduce_worker_histograms(&fractal, buffer);
		failed |= verify_worker_reduction(&fractal, 0, buffer);
	}
	combine_buff_set_var(fractal.densities, 0, fractal.buffs,
		fractal.width, fractal.height);
	expected = 36.0;
	if (fractal.densities[0][0][0] != expected
		|| fractal.densities[3][0][0] != 900.0)
	{
		fprintf(stderr, "Multibuffer mean/variance mismatch: %.17g %.17g\n",
			fractal.densities[0][0][0], fractal.densities[3][0][0]);
		failed = 1;
	}
	teardown_case(&fractal);
	return (failed);
}

static int	render_multibuffer_case(t_fractal *fractal)
{
	int	channel;
	int	failed;

	failed = 0;
	channel = -1;
	while (++channel < CHANNELS)
	{
		buddha_render_channel(fractal,
			((int [CHANNELS]){fractal->buddha->min1,
				fractal->buddha->min2, fractal->buddha->min3})[channel],
			((int [CHANNELS]){fractal->buddha->max1,
				fractal->buddha->max2, fractal->buddha->max3})[channel],
			channel);
	}
	if (buddha_nlm(fractal) != 0)
		return (fprintf(stderr, "Test NLM allocation failed\n"), 1);
	return (failed);
}

static int	test_multibuffer_determinism(t_btype type)
{
	t_fractal	fractal;
	t_buddha	buddha;
	double		*reference;
	size_t		channel_size;
	int			channel;
	int			y;
	int			failed;

	if (setup_case_config(&fractal, &buddha, type, 4, 3) != 0)
		return (fprintf(stderr, "Multibuffer determinism setup failed\n"), 1);
	channel_size = (size_t)fractal.size * sizeof(*reference);
	reference = malloc(CHANNELS * channel_size);
	if (!reference)
	{
		teardown_case(&fractal);
		return (fprintf(stderr, "Multibuffer snapshot failed\n"), 1);
	}
	failed = render_multibuffer_case(&fractal);
	channel = -1;
	while (++channel < CHANNELS)
	{
		y = -1;
		while (++y < fractal.height)
			memcpy(reference + (size_t)channel * (size_t)fractal.size
				+ (size_t)y * (size_t)fractal.width,
				fractal.densities[channel][y],
				(size_t)fractal.width * sizeof(*reference));
	}
	failed |= render_multibuffer_case(&fractal);
	channel = -1;
	while (++channel < CHANNELS)
	{
		y = -1;
		while (++y < fractal.height)
		{
			if (memcmp(reference + (size_t)channel * (size_t)fractal.size
					+ (size_t)y * (size_t)fractal.width,
					fractal.densities[channel][y],
					(size_t)fractal.width * sizeof(*reference)) != 0)
			{
				fprintf(stderr,
					"Multibuffer NLM render type %d was not deterministic\n",
					type);
				failed = 1;
				channel = CHANNELS;
				break ;
			}
		}
	}
	free(reference);
	teardown_case(&fractal);
	return (failed);
}

static void	snapshot_density_channels(t_fractal *fractal, int first,
		double *snapshot)
{
	int	channel;
	int	y;

	channel = -1;
	while (++channel < CHANNELS)
	{
		y = -1;
		while (++y < fractal->height)
			memcpy(snapshot + (size_t)channel * (size_t)fractal->size
				+ (size_t)y * (size_t)fractal->width,
				fractal->densities[first + channel][y],
				(size_t)fractal->width * sizeof(*snapshot));
	}
}

static bool	density_channels_match(t_fractal *fractal, int first,
		const double *snapshot)
{
	int	channel;
	int	y;

	channel = -1;
	while (++channel < CHANNELS)
	{
		y = -1;
		while (++y < fractal->height)
			if (memcmp(snapshot + (size_t)channel * (size_t)fractal->size
					+ (size_t)y * (size_t)fractal->width,
					fractal->densities[first + channel][y],
					(size_t)fractal->width * sizeof(*snapshot)) != 0)
				return (false);
	}
	return (true);
}

static int	render_channels_without_nlm(t_fractal *fractal)
{
	int	channel;

	channel = -1;
	while (++channel < CHANNELS)
		buddha_render_channel(fractal,
			((int [CHANNELS]){fractal->buddha->min1,
				fractal->buddha->min2, fractal->buddha->min3})[channel],
			((int [CHANNELS]){fractal->buddha->max1,
				fractal->buddha->max2, fractal->buddha->max3})[channel],
			channel);
	return (0);
}

static int	test_two_buffer_nlm_retuning(void)
{
	t_fractal	fractal;
	t_buddha	buddha;
	double		*raw;
	double		*filtered;
	double		*variance;
	size_t		bytes;
	int			failed;

	if (setup_case_config(&fractal, &buddha, BUDDHA1, 2, 2) != 0)
		return (fprintf(stderr, "Two-buffer NLM setup failed\n"), 1);
	bytes = (size_t)CHANNELS * (size_t)fractal.size * sizeof(*raw);
	raw = malloc(bytes);
	filtered = malloc(bytes);
	variance = malloc(bytes);
	if (!raw || !filtered || !variance)
	{
		free(raw);
		free(filtered);
		free(variance);
		teardown_case(&fractal);
		return (fprintf(stderr, "Two-buffer NLM snapshot failed\n"), 1);
	}
	failed = fractal.histograms != BUDDHA_NLM_MATRICES;
	render_channels_without_nlm(&fractal);
	snapshot_density_channels(&fractal, 0, raw);
	failed |= buddha_nlm(&fractal) != 0;
	failed |= !buddha.nlm_variance_ready || !buddha.nlm_filtered_ready
		|| !buddha.nlm_show_filtered;
	snapshot_density_channels(&fractal, 0, filtered);
	snapshot_density_channels(&fractal, 3, variance);
	failed |= !density_channels_match(&fractal, 6, raw);
	failed |= !buddha_nlm_toggle_output(&fractal);
	failed |= buddha.nlm_show_filtered
		|| !density_channels_match(&fractal, 0, raw);
	failed |= !buddha_nlm_toggle_output(&fractal);
	failed |= !buddha.nlm_show_filtered
		|| !density_channels_match(&fractal, 0, filtered);
	buddha.nlm_kc += 0.25;
	failed |= buddha_nlm(&fractal) != 0;
	failed |= !density_channels_match(&fractal, 3, variance)
		|| !density_channels_match(&fractal, 6, raw);
	failed |= !buddha_nlm_toggle_output(&fractal);
	failed |= buddha.nlm_show_filtered
		|| !density_channels_match(&fractal, 0, raw);
	failed |= buddha_nlm(&fractal) != 0;
	failed |= !buddha.nlm_show_filtered
		|| !density_channels_match(&fractal, 3, variance)
		|| !density_channels_match(&fractal, 6, raw);
	if (failed)
		fprintf(stderr, "Two-buffer NLM retention/retuning failed\n");
	free(raw);
	free(filtered);
	free(variance);
	teardown_case(&fractal);
	return (failed);
}

static int	test_workspace_reuse(void)
{
	t_fractal	fractal;
	t_buddha	buddha;
	double		***densities;
	double		**workers;
	int			failed;

	if (setup_case(&fractal, &buddha, BUDDHA1) != 0)
		return (fprintf(stderr, "Workspace reuse setup failed\n"), 1);
	densities = fractal.densities;
	workers = fractal.worker_histograms;
	failed = buddha_ensure_workspace(&fractal) != 0;
	if (fractal.densities != densities
		|| fractal.worker_histograms != workers)
	{
		fprintf(stderr, "Unchanged Buddha workspace was reallocated\n");
		failed = 1;
	}
	teardown_case(&fractal);
	return (failed);
}

static int	test_importance_capture(void)
{
	t_fractal	fractal;
	t_buddha	buddha;
	double		rgb[3];
	int			channel;
	int			failed;

	if (setup_case(&fractal, &buddha, BUDDHA1) != 0)
		return (fprintf(stderr, "Importance capture setup failed\n"), 1);
	fractal.width_orig = fractal.width;
	fractal.height_orig = fractal.height;
	buddha_importance_begin(&fractal);
	failed = (buddha.importance_values != NULL
			|| buddha.render_pixels != NULL);
	buddha.importance_enabled = true;
	buddha_importance_begin(&fractal);
	if (!buddha.importance_values || !buddha.render_pixels)
		failed = 1;
	channel = -1;
	while (++channel < CHANNELS)
	{
		zero_matrix(fractal.densities[channel],
			fractal.width, fractal.height);
		fractal.densities[channel][0][0] = 100.0;
		fractal.densities[channel][0][1] = 25.0;
		buddha_importance_capture(&fractal, channel);
	}
	if (!buddha.importance_ready
		|| buddha.importance_values[0] != 65535U
		|| buddha.importance_values[1] != 65535U
		|| buddha.importance_values[2] != 65535U
		|| buddha.importance_values[3] == 0U
		|| buddha.importance_values[3] >= 65535U
		|| buddha.importance_values[3] % 257U == 0U
		|| buddha.importance_values[3] != buddha.importance_values[4]
		|| buddha.importance_values[4] != buddha.importance_values[5])
	{
		fprintf(stderr,
			"Importance 16-bit capture was not normalized correctly\n");
		failed = 1;
	}
	buddha.importance_mode = BUDDHA_IMPORTANCE_BLUE;
	buddha_importance_pixel_rgb(&fractal, 0, 0, rgb);
	failed |= rgb[0] != 0.0 || rgb[1] != 0.0 || rgb[2] != 1.0;
	buddha.importance_mode = BUDDHA_IMPORTANCE_GREEN;
	buddha_importance_pixel_rgb(&fractal, 0, 0, rgb);
	failed |= rgb[0] != 0.0 || rgb[1] != 1.0 || rgb[2] != 0.0;
	buddha.importance_mode = BUDDHA_IMPORTANCE_RED;
	buddha_importance_pixel_rgb(&fractal, 0, 0, rgb);
	failed |= rgb[0] != 1.0 || rgb[1] != 0.0 || rgb[2] != 0.0;
	if (failed)
		fprintf(stderr, "Importance channel view selection failed\n");
	free(buddha.importance_values);
	free(buddha.render_pixels);
	buddha.importance_values = NULL;
	buddha.render_pixels = NULL;
	teardown_case(&fractal);
	return (failed);
}

static const char	*find_png_text(png_text *text, int count,
		const char *key)
{
	int	index;

	index = -1;
	while (++index < count)
		if (strcmp(text[index].key, key) == 0)
			return (text[index].text);
	return (NULL);
}

static int	verify_export_metadata(const char *path, int fractal_id,
		const char *specific_key)
{
	png_structp	png;
	png_infop	info;
	png_textp	text;
	const char	*value;
	FILE		*file;
	int			color_type;
	int			bit_depth;
	int			intent;
	int			count;
	int			failed;

	file = fopen(path, "rb");
	if (!file)
		return (fprintf(stderr, "Could not open export regression PNG\n"), 1);
	png = png_create_read_struct(PNG_LIBPNG_VER_STRING, NULL, NULL, NULL);
	info = NULL;
	if (!png)
		return (fclose(file), 1);
	info = png_create_info_struct(png);
	if (!info || setjmp(png_jmpbuf(png)))
		return (png_destroy_read_struct(&png, &info, NULL), fclose(file), 1);
	png_init_io(png, file);
	png_read_info(png, info);
	color_type = png_get_color_type(png, info);
	bit_depth = png_get_bit_depth(png, info);
	count = png_get_text(png, info, &text, NULL);
	failed = color_type != PNG_COLOR_TYPE_RGB || bit_depth != 16;
	failed |= png_get_sRGB(png, info, &intent) == 0;
	value = find_png_text(text, count, "Metadata Version");
	failed |= !value || strcmp(value, "fractol-render-v3") != 0;
	value = find_png_text(text, count, "Fractal");
	failed |= !value || !strstr(value,
			(char *[5]){"", "Mandelbrot", "Julia",
				"Buddhabrot", "Barnsley Fern"}[fractal_id]);
	value = find_png_text(text, count, "Output Size");
	failed |= !value || strcmp(value, "width=2;height=2") != 0;
	value = find_png_text(text, count, "PNG Encoding");
	failed |= !value || !strstr(value, "depth=16")
		|| !strstr(value, "writer=streaming-rows");
	failed |= find_png_text(text, count, specific_key) == NULL;
	if (fractal_id == 3)
	{
		value = find_png_text(text, count, "CLI Baseline");
		failed |= !value || !strstr(value, "--center -0x1.ae147ae147ae1p-3")
			|| !strstr(value, "--zoom 0x1.3333333333333p+0");
		value = find_png_text(text, count, "View");
		failed |= !value || !strstr(value, "center_real=")
			|| !strstr(value, "center_imaginary=");
		value = find_png_text(text, count, "Buddha Tone Mode");
		failed |= !value || !strstr(value, "negative_mode=safe inverse")
			|| !strstr(value, "normalization=channel percentiles");
		value = find_png_text(text, count, "Buddha Hybrid Tone");
		failed |= !value || !strstr(value, "background=B3D38E")
			|| !strstr(value, "foreground=29314F");
		value = find_png_text(text, count, "Buddha Formula");
		failed |= !value || !strstr(value, "orbit_cache=1")
			|| !strstr(value, "orbit_cache_points=512")
			|| !strstr(value, "interior_rejection=1");
		value = find_png_text(text, count, "Buddha Importance View");
		failed |= !value || !strstr(value, "mode=RGB")
			|| !strstr(value,
				"capture=double-log1p-block-average-to-u16");
	}
	png_destroy_read_struct(&png, &info, NULL);
	fclose(file);
	if (failed)
		fprintf(stderr, "Export metadata regression failed for fractal %d\n",
			fractal_id);
	return (failed);
}

static void	setup_export_fractal(t_fractal *fractal, t_buddha *buddha,
		t_img *image, int fractal_id)
{
	memset(fractal, 0, sizeof(*fractal));
	memset(buddha, 0, sizeof(*buddha));
	fractal->id = fractal_id;
	fractal->width_orig = 2;
	fractal->height_orig = 2;
	fractal->width = 2;
	fractal->height = 2;
	fractal->size = 4;
	fractal->zoom = 1.2;
	fractal->move_x = -0.21;
	fractal->bound = 4.0;
	fractal->max_i = 80;
	fractal->num_colors = 360;
	fractal->col_i = 7;
	fractal->s_kernel = 3;
	fractal->num_rows = 2;
	fractal->num_cols = 1;
	fractal->aspect = 1.0;
	fractal->julia_x = -0.8;
	fractal->julia_y = 0.156;
	fractal->species = 1;
	fractal->colors = (t_4colors){0x112233, 0x445566,
		0x778899, 0xAABBCC};
	fractal->img = *image;
	if (fractal_id != 3)
		return ;
	fractal->buddha = buddha;
	fractal->buffs = 3;
	fractal->complex_f = &square_complex;
	buddha->type = BUDDHA1;
	buddha->n = 8.0;
	buddha->map_n = 7.0;
	buddha->importance_rms = true;
	buddha->square_specialized = true;
	buddha->orbit_cache = true;
	buddha->interior_rejection = true;
	buddha->min1 = 0;
	buddha->max1 = 50;
	buddha->min2 = 0;
	buddha->max2 = 500;
	buddha->min3 = 0;
	buddha->max3 = 5000;
	buddha->white_percentile = 0.999;
	buddha->normalization = BUDDHA_NORM_CHANNEL_PERCENTILE;
	buddha->negative_mode = BUDDHA_NEGATIVE_INVERSE;
	buddha->global_exposure = 1.0;
	buddha->hybrid_spill = BUDDHA_HYBRID_SPILL;
	buddha->hybrid_background = BUDDHA_HYBRID_BACKGROUND;
	buddha->hybrid_foreground = BUDDHA_HYBRID_FOREGROUND;
	buddha->nlm_enabled = true;
	buddha->nlm_patch_radius = 2;
	buddha->nlm_search_radius = 15;
	buddha->nlm_kc = 1.0;
	buddha->nlm_noise_scale = 1.0 / 3.0;
}

static int	test_export_metadata(void)
{
	unsigned int	pixels[4];
	t_fractal		fractal;
	t_buddha		buddha;
	t_img			image;
	png_text		*text;
	int				fractal_id;
	int				failed;
	int				fd;

	pixels[0] = 0x00112233;
	pixels[1] = 0x00445566;
	pixels[2] = 0x00778899;
	pixels[3] = 0x00AABBCC;
	image = (t_img){NULL, (char *)pixels, 32, 0, 2 * 4};
	failed = 0;
	fractal_id = 0;
	while (++fractal_id <= 4)
	{
		char	path[] = "/tmp/fractol-export-XXXXXX.png";

		setup_export_fractal(&fractal, &buddha, &image, fractal_id);
		text = build_fractal_text(&fractal);
		if (!text)
			return (fprintf(stderr, "Export metadata setup failed\n"), 1);
		fd = mkstemps(path, 4);
		if (fd == -1)
			return (fprintf(stderr, "Export temp file setup failed\n"), 1);
		close(fd);
		if (export_png16(path, &fractal, text) != 0)
			failed = 1;
		else
			failed |= verify_export_metadata(path, fractal_id,
					(char *[5]){"", "Color", "Julia Constant",
						"Buddha NLM", "Fern"}[fractal_id]);
		unlink(path);
	}
	return (failed);
}

static int	read_png_red16(const char *path, uint16_t *red,
		const char *expected_source)
{
	png_byte	row[6];
	png_structp	png;
	png_infop	info;
	png_textp	text;
	const char	*encoding;
	FILE		*file;
	int			count;

	file = fopen(path, "rb");
	if (!file)
		return (-1);
	png = png_create_read_struct(PNG_LIBPNG_VER_STRING, NULL, NULL, NULL);
	info = NULL;
	if (!png)
		return (fclose(file), -1);
	info = png_create_info_struct(png);
	if (!info || setjmp(png_jmpbuf(png)))
		return (png_destroy_read_struct(&png, &info, NULL), fclose(file), -1);
	png_init_io(png, file);
	png_read_info(png, info);
	if (png_get_bit_depth(png, info) != 16
		|| png_get_color_type(png, info) != PNG_COLOR_TYPE_RGB
		|| png_get_rowbytes(png, info) != sizeof(row))
		return (png_destroy_read_struct(&png, &info, NULL), fclose(file), -1);
	count = png_get_text(png, info, &text, NULL);
	encoding = find_png_text(text, count, "PNG Encoding");
	if (expected_source && (!encoding || !strstr(encoding, expected_source)))
		return (png_destroy_read_struct(&png, &info, NULL), fclose(file), -1);
	png_read_row(png, row, NULL);
	*red = (uint16_t)(((uint16_t)row[0] << 8) | row[1]);
	png_destroy_read_struct(&png, &info, NULL);
	fclose(file);
	return (0);
}

static int	export_red16(t_fractal *fractal, uint16_t *red,
		const char *expected_source)
{
	char		path[] = "/tmp/fractol-16bit-XXXXXX.png";
	png_text	*text;
	int			fd;
	int			failed;

	fd = mkstemps(path, 4);
	if (fd == -1)
		return (-1);
	close(fd);
	text = NULL;
	if (expected_source)
		text = build_fractal_text(fractal);
	if (expected_source && !text)
		return (unlink(path), -1);
	failed = export_png16(path, fractal, text) != 0;
	if (!failed)
		failed = read_png_red16(path, red, expected_source) != 0;
	unlink(path);
	return (failed * -1);
}

static void	setup_16bit_buddha(t_fractal *fractal, t_buddha *buddha,
		double ***densities)
{
	memset(fractal, 0, sizeof(*fractal));
	memset(buddha, 0, sizeof(*buddha));
	fractal->id = 3;
	fractal->width = 1;
	fractal->height = 1;
	fractal->width_orig = 1;
	fractal->height_orig = 1;
	fractal->buddha = buddha;
	fractal->densities = densities;
	buddha->bpow = 0.5;
	buddha->gpow = 0.5;
	buddha->rpow = 0.5;
	buddha->white_b = 100.0;
	buddha->white_g = 100.0;
	buddha->white_r = 100.0;
	buddha->high_b = 100.0;
	buddha->high_g = 100.0;
	buddha->high_r = 100.0;
	buddha->exposure_b = 1.0;
	buddha->exposure_g = 1.0;
	buddha->exposure_r = 1.0;
	buddha->global_exposure = 1.0;
	buddha->negative_mode = BUDDHA_NEGATIVE_INVERSE;
}

static int	test_16bit_buddha_export(void)
{
	double			blue_value[1];
	double			green_value[1];
	double			red_value[1];
	double			*blue[1];
	double			*green[1];
	double			*red[1];
	double			**densities[3];
	t_fractal		fractal;
	t_buddha		buddha;
	double			rgb[3];
	uint16_t		red16;

	blue_value[0] = 25.0;
	green_value[0] = 25.0;
	red_value[0] = 25.0;
	blue[0] = blue_value;
	green[0] = green_value;
	red[0] = red_value;
	densities[0] = blue;
	densities[1] = green;
	densities[2] = red;
	setup_16bit_buddha(&fractal, &buddha, densities);
	buddha_pixel_rgb(&fractal, 0, 0, rgb);
	if (!close_enough(rgb[0], 0.5L))
		return (fprintf(stderr, "Buddha tone was quantized before export\n"), 1);
	if (export_red16(&fractal, &red16, NULL) != 0)
		return (fprintf(stderr, "16-bit Buddha export failed\n"), 1);
	if (red16 != 32768 || red16 % 257 == 0)
		return (fprintf(stderr,
				"16-bit Buddha export was reduced to replicated 8-bit\n"), 1);
	buddha.filter = true;
	buddha.ftype = ADJUST;
	buddha.flevel = 3;
	if (export_red16(&fractal, &red16,
			"source=density-double-tone-adjust") != 0 || red16 != 49151)
		return (fprintf(stderr,
				"16-bit Buddha adjustment export failed\n"), 1);
	buddha.ftype = GAUSS;
	buddha.flevel = 5;
	if (export_red16(&fractal, &red16,
			"source=density-double-tone-gaussian") != 0 || red16 != 32768)
		return (fprintf(stderr,
				"16-bit Buddha Gaussian export failed\n"), 1);
	buddha.filter = false;
	buddha.negative_mode = BUDDHA_NEGATIVE_HYBRID;
	buddha.bpow = -0.2;
	buddha.gpow = -0.2;
	buddha.rpow = -0.2;
	buddha.hybrid_spill = 0.2;
	buddha.hybrid_background = BUDDHA_HYBRID_BACKGROUND;
	buddha.hybrid_foreground = BUDDHA_HYBRID_FOREGROUND;
	buddha.tone_default.power[0] = 0.41;
	buddha.tone_default.power[1] = 0.39;
	buddha.tone_default.power[2] = 0.34;
	buddha.tone_default.exposure[0] = 1.0;
	buddha.tone_default.exposure[1] = 1.0;
	buddha.tone_default.exposure[2] = 1.0;
	buddha_pixel_rgb(&fractal, 0, 0, rgb);
	red16 = (uint16_t)floor(rgb[0] * 65535.0 + 0.5);
	if (red16 % 257 == 0)
		return (fprintf(stderr, "Hybrid tone remained byte-quantized\n"), 1);
	return (0);
}

static int	test_16bit_importance_export(void)
{
	t_fractal	fractal;
	t_buddha	buddha;
	uint16_t	values[3];
	uint16_t	red16;
	png_text	*text;
	int			fd;
	char		path[] = "/tmp/fractol-importance16-XXXXXX.png";

	memset(&fractal, 0, sizeof(fractal));
	memset(&buddha, 0, sizeof(buddha));
	values[0] = 12345;
	values[1] = 23456;
	values[2] = 34567;
	fractal.id = 3;
	fractal.width = 1;
	fractal.height = 1;
	fractal.width_orig = 1;
	fractal.height_orig = 1;
	fractal.size = 1;
	fractal.zoom = 1.2;
	fractal.buddha = &buddha;
	buddha.importance_enabled = true;
	buddha.importance_ready = true;
	buddha.importance_view = true;
	buddha.importance_mode = BUDDHA_IMPORTANCE_RED;
	buddha.importance_values = values;
	text = build_fractal_text(&fractal);
	if (!text)
		return (fprintf(stderr,
				"16-bit importance metadata setup failed\n"), 1);
	fd = mkstemps(path, 4);
	if (fd == -1)
		return (1);
	close(fd);
	if (export_png16(path, &fractal, text) != 0
		|| read_png_red16(path, &red16,
			"source=importance-density-double-tone") != 0)
		return (unlink(path), fprintf(stderr,
				"16-bit importance export failed\n"), 1);
	unlink(path);
	if (red16 != values[2] || red16 % 257 == 0)
		return (fprintf(stderr,
				"Importance export was reduced to replicated 8-bit\n"), 1);
	return (0);
}

static uint64_t	benchmark_escape_grid(t_comps comps, bool specialized)
{
	t_complex	c;
	uint64_t	checksum;
	int			repeat;
	int			x;
	int			y;

	comps.square_formula = specialized;
	comps.interior_rejection = false;
	comps.b_max_i = 2000;
	checksum = 0;
	repeat = -1;
	while (++repeat < 8)
	{
		y = -1;
		while (++y < 96)
		{
			x = -1;
			while (++x < 96)
			{
				c.x = -2.0 + ((double)x + 0.5) * (4.0 / 96.0);
				c.y = 2.0 - ((double)y + 0.5) * (4.0 / 96.0);
				checksum += (uint64_t)buddha_escape_length(
						c, comps, comps.b_max_i);
			}
		}
	}
	return (checksum);
}

static long	benchmark_tracking_variant(t_comps comps, double *density,
		size_t samples, bool interior_rejection, bool cache_enabled)
{
	t_complex	cache[BUDDHA_ORBIT_CACHE_POINTS];
	t_complex	c;
	Xoro128		rng;
	long		start;
	size_t		sample;

	memset(density, 0, (size_t)comps.width * (size_t)comps.height
		* sizeof(*density));
	comps.density_flat = density;
	comps.interior_rejection = interior_rejection;
	sxoro128(&rng, 0xC0FFEE1234ULL);
	start = get_time();
	sample = 0;
	while (sample++ < samples)
	{
		c.x = (xoro128d(&rng) * comps.sample_x_span + comps.sample_x_min)
			* comps.inv_zoom + comps.move_x;
		c.y = (xoro128d(&rng) * -comps.sample_y_span - comps.sample_y_min)
			* comps.inv_zoom - comps.move_y;
		buddha_iteration(c, 1.0, comps,
			(t_complex *[2]){NULL, cache}[cache_enabled]);
	}
	return (get_time() - start);
}

static int	benchmark_tracking(t_comps comps, int max_iterations,
		size_t samples)
{
	double	*baseline;
	double	*interior;
	double	*cached;
	size_t	bytes;
	long	baseline_time;
	long	interior_time;
	long	cached_time;
	int		failed;

	bytes = (size_t)comps.width * (size_t)comps.height * sizeof(*baseline);
	baseline = malloc(bytes);
	interior = malloc(bytes);
	cached = malloc(bytes);
	if (!baseline || !interior || !cached)
		return (free(baseline), free(interior), free(cached), 1);
	comps.b_min_i = 0;
	comps.b_max_i = max_iterations;
	comps.square_formula = true;
	baseline_time = benchmark_tracking_variant(comps, baseline, samples,
			false, false);
	interior_time = benchmark_tracking_variant(comps, interior, samples,
			true, false);
	cached_time = benchmark_tracking_variant(comps, cached, samples,
			true, true);
	failed = memcmp(baseline, interior, bytes) != 0
		|| memcmp(baseline, cached, bytes) != 0;
	printf("Orbit tracking max=%d samples=%zu: two-pass=%ld ms "
		"interior=%ld ms cached=%ld ms speedup=%.2fx\n",
		max_iterations, samples, baseline_time, interior_time, cached_time,
		(double)baseline_time / (double)cached_time);
	free(baseline);
	free(interior);
	free(cached);
	return (failed);
}

static int	benchmark_render_hot_path(int channel, const char *label)
{
	t_fractal	fractal;
	t_buddha	buddha;
	double		*baseline;
	size_t		bytes;
	long		two_pass_time;
	long		interior_time;
	long		cached_time;
	long		start;
	int			minimum[3];
	int			maximum[3];
	int			y;
	int			failed;

	if (setup_case_config_size(&fractal, &buddha, BUDDHA1, 4, 1, 128) != 0)
		return (1);
	buddha.n = 4.0;
	buddha.map_n = 3.0;
	minimum[0] = buddha.min1;
	minimum[1] = buddha.min2;
	minimum[2] = buddha.min3;
	maximum[0] = buddha.max1;
	maximum[1] = buddha.max2;
	maximum[2] = buddha.max3;
	bytes = (size_t)fractal.size * sizeof(*baseline);
	baseline = malloc(bytes);
	if (!baseline)
		return (teardown_case(&fractal), 1);
	buddha.orbit_cache = false;
	buddha.interior_rejection = false;
	start = get_time();
	buddha_render_channel(&fractal, minimum[channel], maximum[channel],
		channel);
	two_pass_time = get_time() - start;
	y = -1;
	while (++y < fractal.height)
		memcpy(baseline + (size_t)y * (size_t)fractal.width,
			fractal.densities[channel][y],
			(size_t)fractal.width * sizeof(*baseline));
	buddha.interior_rejection = true;
	start = get_time();
	buddha_render_channel(&fractal, minimum[channel], maximum[channel],
		channel);
	interior_time = get_time() - start;
	failed = 0;
	y = -1;
	while (++y < fractal.height)
		failed |= memcmp(baseline + (size_t)y * (size_t)fractal.width,
				fractal.densities[channel][y],
				(size_t)fractal.width * sizeof(*baseline)) != 0;
	buddha.orbit_cache = true;
	start = get_time();
	buddha_render_channel(&fractal, minimum[channel], maximum[channel],
		channel);
	cached_time = get_time() - start;
	y = -1;
	while (++y < fractal.height)
		failed |= memcmp(baseline + (size_t)y * (size_t)fractal.width,
				fractal.densities[channel][y],
				(size_t)fractal.width * sizeof(*baseline)) != 0;
	printf("Buddha %s render 128x128 n=4: two-pass=%ld ms "
		"interior=%ld ms selected=%ld ms speedup=%.2fx\n",
		label, two_pass_time, interior_time, cached_time,
		(double)two_pass_time / (double)cached_time);
	free(baseline);
	teardown_case(&fractal);
	return (failed);
}

static int	benchmark_buddha(void)
{
	t_fractal	fractal;
	t_buddha	buddha;
	t_comps		comps;
	uint64_t	specialized_checksum;
	uint64_t	generic_checksum;
	long		specialized_time;
	long		generic_time;
	long		separate_time;
	long		combined_time;
	long		start;
	int			channel;
	int			repeat;

	if (setup_case_workers(&fractal, &buddha, BUDDHA1, 4) != 0)
		return (fprintf(stderr, "Buddha benchmark setup failed\n"), 1);
	comps = set_comps(&fractal, false);
	start = get_time();
	specialized_checksum = benchmark_escape_grid(comps, true);
	specialized_time = get_time() - start;
	start = get_time();
	generic_checksum = benchmark_escape_grid(comps, false);
	generic_time = get_time() - start;
	buddha.map_n = 2.0;
	buddha.map_adaptive = false;
	buddha.importance_rms = false;
	start = get_time();
	repeat = -1;
	while (++repeat < 20)
	{
		channel = -1;
		while (++channel < 3)
		{
			set_test_channel(&fractal, channel);
			buddha_map(&fractal);
		}
	}
	separate_time = get_time() - start;
	start = get_time();
	repeat = -1;
	while (++repeat < 20)
		buddha_map_all(&fractal);
	combined_time = get_time() - start;
	printf("Square orbit: specialized=%ld ms generic=%ld ms speedup=%.2fx\n",
		specialized_time, generic_time,
		(double)generic_time / (double)specialized_time);
	printf("Importance map: combined=%ld ms separate=%ld ms speedup=%.2fx\n",
		combined_time, separate_time,
		(double)separate_time / (double)combined_time);
	printf("Orbit checksums: specialized=%llu generic=%llu\n",
		(unsigned long long)specialized_checksum,
		(unsigned long long)generic_checksum);
	if (benchmark_tracking(comps, 500, 200000) != 0
		|| benchmark_tracking(comps, 5000, 50000) != 0
		|| benchmark_render_hot_path(1, "green") != 0
		|| benchmark_render_hot_path(2, "red") != 0)
	{
		teardown_case(&fractal);
		return (fprintf(stderr,
				"Cached orbit tracking changed the density\n"), 1);
	}
	teardown_case(&fractal);
	return (specialized_checksum != generic_checksum);
}

static void	fill_nlm_benchmark(t_fractal *fractal)
{
	uint64_t	hash;
	int			channel;
	int			x;
	int			y;

	channel = -1;
	while (++channel < CHANNELS)
	{
		y = -1;
		while (++y < fractal->height)
		{
			x = -1;
			while (++x < fractal->width)
			{
				hash = (uint64_t)(x + 1) * 0x9E3779B185EBCA87ULL;
				hash ^= (uint64_t)(y + 3) * 0xC2B2AE3D27D4EB4FULL;
				hash ^= (uint64_t)(channel + 5) * 0x165667B19E3779F9ULL;
				hash ^= hash >> 29;
				fractal->densities[channel][y][x]
					= 50.0 + (double)(channel + 1) * 20.0
					+ (double)(x + 2 * y) * 0.25
					+ (double)(hash & 1023ULL) * 0.0625;
				fractal->densities[channel + 3][y][x]
					= 4.0 + (double)((hash >> 17) & 255ULL) * 0.03125;
			}
		}
	}
}

static long double	nlm_benchmark_checksum(t_fractal *fractal)
{
	long double	checksum;
	int			channel;
	int			x;
	int			y;

	checksum = 0.0L;
	channel = -1;
	while (++channel < CHANNELS)
	{
		y = -1;
		while (++y < fractal->height)
		{
			x = -1;
			while (++x < fractal->width)
				checksum += (long double)fractal->densities[channel][y][x]
					* (long double)(1 + x + y * fractal->width
						+ channel * fractal->size);
		}
	}
	return (checksum);
}

static int	benchmark_buddha_nlm(void)
{
	t_fractal	fractal;
	t_buddha	buddha;
	long double	first_checksum;
	long double	refilter_checksum;
	long		first_time;
	long		refilter_time;
	long		start;
	int			failed;

	if (setup_case_config_size(&fractal, &buddha, BUDDHA1, 4, 3,
			NLM_BENCH_SIZE) != 0)
		return (fprintf(stderr, "Buddha NLM benchmark setup failed\n"), 1);
	buddha.nlm_patch_radius = 2;
	buddha.nlm_search_radius = 15;
	buddha.nlm_kc = 0.75;
	fill_nlm_benchmark(&fractal);
	start = get_time();
	failed = buddha_nlm(&fractal) != 0;
	first_time = get_time() - start;
	first_checksum = nlm_benchmark_checksum(&fractal);
	start = get_time();
	failed |= buddha_nlm(&fractal) != 0;
	refilter_time = get_time() - start;
	refilter_checksum = nlm_benchmark_checksum(&fractal);
	printf("NLM fixed data %dx%d: first=%ld ms refilter=%ld ms\n",
		NLM_BENCH_SIZE, NLM_BENCH_SIZE, first_time, refilter_time);
	printf("NLM checksums: first=%.21Lg refilter=%.21Lg\n",
		first_checksum, refilter_checksum);
	if (!close_enough(first_checksum, refilter_checksum))
		failed = 1;
	teardown_case(&fractal);
	return (failed);
}

int	main(int argc, char **argv)
{
	int	print_reference;
	int	failed;
	int	i;

	print_reference = (argc == 2
			&& strcmp(argv[1], "--print-reference") == 0);
	if (argc == 2 && strcmp(argv[1], "--benchmark") == 0)
		return (benchmark_buddha());
	if (argc == 2 && strcmp(argv[1], "--benchmark-nlm") == 0)
		return (benchmark_buddha_nlm());
	failed = 0;
	i = -1;
	while (++i < (int)(sizeof(g_reference) / sizeof(g_reference[0])))
		failed |= run_case(&g_reference[i], print_reference);
	failed |= test_tone_mapping();
	failed |= test_post_spill_smoother();
	failed |= test_hybrid_tone();
	failed |= test_sample_budget_guard();
	failed |= test_buddha_start_options();
	failed |= test_importance_allocation();
	failed |= test_combined_map_equivalence();
	failed |= test_map_scale_policy();
	failed |= test_rectangular_geometry_and_display();
	failed |= test_square_specialization();
	failed |= test_parallel_determinism();
	failed |= test_multibuffer_reduction_and_variance();
	failed |= test_multibuffer_determinism(BUDDHA1);
	failed |= test_multibuffer_determinism(BUDDHA2);
	failed |= test_two_buffer_nlm_retuning();
	failed |= test_workspace_reuse();
	failed |= test_importance_capture();
	failed |= test_export_metadata();
	failed |= test_16bit_buddha_export();
	failed |= test_16bit_importance_export();
	if (print_reference)
		return (0);
	if (failed)
		return (fprintf(stderr, "Buddha regression failed\n"), 1);
	printf("Buddha regression passed\n");
	return (0);
}
